### ISSUE TITLE
AttributeError: 'MsmsSpectrum' object has no attribute 'query_identifier'

### ISSUE THREAD

**Issue by vnaum** [bittremieux/ANN-SoLo#10]
Installed ANN-SoLo from conda,  and getting this almost instantly:
```
Library spectra read: 0spectra [00:00, ?spectra/s]
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/ann_solo", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/ann_solo/ann_solo.py", line 64, in main
    spec_lib = spectral_library.SpectralLibrary(
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/ann_solo/spectral_library.py", line 64, in __init__
    self._library_reader = reader.SpectralLibraryReader(
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/ann_solo/reader.py", line 94, in __init__
    self._create_config()
  File "/home/ubuntu/miniconda3/lib/python3.8/site-packages/ann_solo/reader.py", line 137, in _create_config
    info_charge['id'].append(spectrum.query_identifier)
AttributeError: 'MsmsSpectrum' object has no attribute 'query_identifier'
```

Diving into source shows `MsmsSpectrum` comes from `spectrum_utils`, and I see no signs of `query_identifier` ever being there, only `identifier`.
Is there some special spectrum_utils version to be installed?

identifier -> query_identifier comes from commit in ea3a647c2f218ca4f4269e0aa2745a1890f2e017

**Comment by bittremieux** [comment]
Thank you for the detailed bug report. It was indeed an incorrect change in the commit you've mentioned.

The updated version 0.3.2 is available from PyPI.
