### ISSUE TITLE
ann_solo_plot error -- TypeError: __init__() takes from 3 to 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by lindsaypino** [bittremieux/ANN-SoLo#3]
Ran into this while trying to run ann_solo_plot:

```
(base) lindsay@pug:~/proj/cgas_pulldown/results/annsolo_plots$ ann_solo_plot ../annsolo/output_2_high.mztab 093019_822_2_high_129.3346.3346.3
WARNING:root:Missing spectral library configuration file
Library spectra read: 7091spectra [00:00, 16464.49spectra/s]
Traceback (most recent call last):
  File "/home/lindsay/miniconda3/bin/ann_solo_plot", line 10, in <module>
    sys.exit(main())
  File "/home/lindsay/miniconda3/lib/python3.7/site-packages/ann_solo/plot_ssm.py", line 106, in main
    set_matching_peaks(library_spectrum, query_spectrum)
  File "/home/lindsay/miniconda3/lib/python3.7/site-packages/ann_solo/plot_ssm.py", line 28, in set_matching_peaks
    fragment_annotation = FragmentAnnotation('z', 1, 1, 0)
TypeError: __init__() takes from 3 to 4 positional arguments but 5 were given
```

**Comment by bittremieux** [comment]
Fixed in ANN-SoLo v0.2.4. You can update it using pip: `pip install ann_solo --upgrade`.
