### ISSUE TITLE
Can not run the module

### ISSUE THREAD

**Issue by photoszzt** [bittremieux/ANN-SoLo#36]
```
python -m ann_solo.ann_solo --help
Traceback (most recent call last):
  File "/users/zhitingz/miniconda3/envs/work/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/users/zhitingz/miniconda3/envs/work/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/users/zhitingz/miniconda3/envs/work/lib/python3.9/site-packages/ann_solo/__init__.py", line 3, in <module>
    from .ann_solo import ann_solo
  File "/users/zhitingz/miniconda3/envs/work/lib/python3.9/site-packages/ann_solo/ann_solo.py", line 4, in <module>
    from ann_solo import spectral_library
  File "/users/zhitingz/miniconda3/envs/work/lib/python3.9/site-packages/ann_solo/spectral_library.py", line 18, in <module>
    from ann_solo import reader
  File "/users/zhitingz/miniconda3/envs/work/lib/python3.9/site-packages/ann_solo/reader.py", line 17, in <module>
    from ann_solo.parsers import SplibParser
  File "ann_solo/parsers.pyx", line 15, in init ann_solo.parsers
ImportError: cannot import name PeptideFragmentAnnotation
```
Looking at the source code: the spectrum_utils doesn't contain this function.

**Comment by bittremieux** [comment]
The problem is indeed that spectrum_utils doesn't contain `PeptideFragmentAnnotation` anymore since version 0.4. Until we're able to update the spectrum_utils version in ANN-SoLo, I've pinned it now to subversions of 0.3 only.

In your case, to fix this issue, you can do:
```
conda uninstall spectrum_utils && conda install -c bioconda spectrum_utils 
```
If dependencies were installed using conda (as documented in the Wiki). Alternatively, if spectrum_utils was installed using pip, use the following:
```
pip uninstall spectrum_utils && pip install spectrum_utils==0.3.5
```
