### ISSUE TITLE
Problem with v0.3.0 pip install

### ISSUE THREAD

**Issue by wfondrie** [bittremieux/ANN-SoLo#8]
I tried installing the version 0.3.0 via `pip` and ran into this issue on both my Mac and Google Colab:
```
(base) $ pip install ann_solo
Collecting ann_solo
  Using cached ann_solo-0.3.0.tar.gz (397 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/Caskroom/miniconda/base/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/privat /var/folders/kz/w4rz5ym12sj4rz3_p657v3br0000gn/T/pip-install-e9hu9kfw/ann-solo/setup.py'"'"'; __file__='"'"'/private/var/folders/kz/w4rz5ym12sj4rz3_p657v3br0000gn/T/pip-install-e9hu9kfw/ann-solo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/kz/w4rz5ym12sj4rz3_p657v3br0000gn/T/pip-pip-egg-info-zbrkw9w8
         cwd: /private/var/folders/kz/w4rz5ym12sj4rz3_p657v3br0000gn/T/pip-install-e9hu9kfw/ann-solo/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kz/w4rz5ym12sj4rz3_p657v3br0000gn/T/pip-install-e9hu9kfw/ann-solo/setup.py", line 5, in <module>
        import ann_solo
      File "/private/var/folders/kz/w4rz5ym12sj4rz3_p657v3br0000gn/T/pip-install-e9hu9kfw/ann-solo/ann_solo/__init__.py", line 3, in <module>
        from .ann_solo import ann_solo
      File "/private/var/folders/kz/w4rz5ym12sj4rz3_p657v3br0000gn/T/pip-install-e9hu9kfw/ann-solo/ann_solo/ann_solo.py", line 4, in <module>
        from ann_solo import spectral_library
      File "/private/var/folders/kz/w4rz5ym12sj4rz3_p657v3br0000gn/T/pip-install-e9hu9kfw/ann-solo/ann_solo/spectral_library.py", line 18, in <module>
        from ann_solo import reader
      File "/private/var/folders/kz/w4rz5ym12sj4rz3_p657v3br0000gn/T/pip-install-e9hu9kfw/ann-solo/ann_solo/reader.py", line 17, in <module>
        from ann_solo.parsers import SplibParser
    ModuleNotFoundError: No module named 'ann_solo.parsers'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It is also worth noting that I do not encounter this error when I install from the source directly with `cd src && python setup.py install` or `cd src && pip install -e .`

**Comment by bittremieux** [comment]
Thank you for reporting. It should be fixed in version 0.3.1, which you can get from PyPI.
